name: Build Windows EXE

on:
  workflow_dispatch:
  push:
    tags:
      - v*

env:
  APP_NAME: iwrqk

permissions:
  contents: write

jobs:
  build_windows_exe:
    name: Build EXE
    runs-on: windows-latest
    outputs:  # 关键点1：定义输出变量
      artifact_name: ${{ steps.set_artifact.outputs.name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Windows EXE
        run: flutter build windows --release

      - name: Verify file structure (关键点2：路径验证)
        run: |
          cd build/windows/runner/Release
          ls -al  # 显示详细文件列表
          [ -f "${{ env.APP_NAME }}.exe" ] || exit 1

      - name: Generate unique artifact name
        id: set_artifact
        shell: bash
        run: |
          timestamp=$(date +%s)
          echo "name=windows_${timestamp}_${{ github.run_number }}" >> $GITHUB_OUTPUT

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.set_artifact.outputs.name }}  # 关键点3：动态名称
          path: |
            build/windows/runner/Release/${{ env.APP_NAME }}.exe
            build/windows/runner/Release/*.dll
            build/windows/runner/Release/data/
          if-no-files-found: error  # 关键点4：严格模式

  publish_release:
    needs: build_windows_exe
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build_windows_exe.outputs.artifact_name }}  # 关键点5：匹配动态名称

      - name: Verify downloaded files
        run: |
          ls -R  # 递归显示文件结构
          [ -f "${{ env.APP_NAME }}.exe" ] || exit 1

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ env.APP_NAME }}.exe
            *.dll
            data/**/*
          tag_name: ${{ github.ref_name || 'manual-' + github.run_id }}
          generate_release_notes: true
