name: Build Windows EXE

on:
  workflow_dispatch:  # 仅手动触发

env:
  APP_NAME: iwrqk

permissions:
  contents: write

jobs:
  build_windows_exe:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build EXE
        run: flutter build windows --release

      - name: Get version
        id: get_version
        shell: bash
        run: |
          echo "version=$(grep -m1 version: pubspec.yaml | awk '{print $2}' | sed 's/\"//g')" >> $GITHUB_OUTPUT

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-exe
          path: build/windows/runner/Release/*.exe  # 直接上传 EXE
