name: Build Windows EXE

on:
  workflow_dispatch:  # 手动触发
  push:
    tags:             # 标签触发（可选保留）
      - v*

env:
  APP_NAME: iwrqk

permissions:
  contents: write

jobs:
  build_windows_exe:
    name: Build EXE
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # 同步升级 checkout 到 v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Windows EXE
        run: flutter build windows --release

      - name: Get version
        id: get_version
        shell: bash
        run: |
          version=$(grep -m1 version: pubspec.yaml | awk '{print $2}' | sed 's/"//g')
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Upload EXE and Dependencies
        uses: actions/upload-artifact@v4  # 升级到 v4
        with:
          name: windows-release
          path: |
            build/windows/runner/Release/*.exe
            build/windows/runner/Release/*.dll
            build/windows/runner/Release/data/**

  publish_release:
    if: ${{ success() && (github.event_name == 'push' || github.event_name == 'workflow_dispatch') }}
    needs: build_windows_exe
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4  # 同步升级到 v4
        with:
          name: windows-release
          path: release_files

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: release_files/*
          tag_name: ${{ github.ref_name || 'manual-' }}${{ github.run_id }}
          generate_release_notes: true
