name: Build Windows EXE

on:
  workflow_dispatch:
  push:
    tags:
      - v*

env:
  APP_NAME: iwrqk

permissions:
  contents: write

jobs:
  build_windows_exe:
    name: Build EXE
    runs-on: windows-latest
    outputs:
      artifact_name: ${{ steps.set_artifact_name.outputs.name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Windows EXE
        run: flutter build windows --release

      - name: Verify build files
        run: |
          ls -R build/windows/runner/Release
          [ -f build/windows/runner/Release/${{ env.APP_NAME }}.exe ] || exit 1

      - name: Generate artifact name
        id: set_artifact_name
        shell: bash
        run: |
          timestamp=$(date +%Y%m%d-%H%M%S)
          echo "name=windows-release-$timestamp-${{ github.run_id }}" >> $GITHUB_OUTPUT

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.set_artifact_name.outputs.name }}
          path: |
            build/windows/runner/Release/*.exe
            build/windows/runner/Release/*.dll
            build/windows/runner/Release/data/
          retention-days: 1  # 自动清理旧产物

  publish_release:
    needs: build_windows_exe
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build_windows_exe.outputs.artifact_name }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ env.APP_NAME }}.exe
            *.dll
            data/**/*
          tag_name: ${{ github.ref_name || 'manual-' + github.run_id }}
          generate_release_notes: true
